# Generated by Django 2.1.2 on 2018-10-15 10:24

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leaveobject', models.CharField(choices=[('sthday', '事假'), ('illday', '病假'), ('year', '年休')], default='年休', max_length=25)),
                ('checkedname', models.CharField(max_length=20, verbose_name='审核人')),
                ('reason', models.CharField(max_length=50, verbose_name='请假理由')),
                ('applytime', models.DateField(auto_now=True, verbose_name='申请时间')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='请假起始日期')),
                ('endday', models.DateField(auto_now_add=True, verbose_name='请假结束日期')),
                ('statu', models.CharField(choices=[('pass', '通过'), ('refuse', '拒绝'), ('weipifu', '未批复')], default='未批复', max_length=10, verbose_name='批复状态')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('receiver', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Out',
            fields=[
                ('out_id', models.AutoField(primary_key=True, serialize=False)),
                ('distingction', models.CharField(max_length=25, verbose_name='目的地')),
                ('checkedname', models.CharField(max_length=20, verbose_name='审核人')),
                ('reason', models.CharField(max_length=50, verbose_name='外出事由')),
                ('applytime', models.DateField(auto_now=True, verbose_name='申请时间')),
                ('startday', models.DateField(auto_now_add=True, verbose_name='外出起始日期')),
                ('endday', models.DateField(auto_now_add=True, verbose_name='外出结束日期')),
                ('statu', models.CharField(choices=[('pass', '通过'), ('refuse', '拒绝'), ('weipifu', '未批复')], default='未批复', max_length=10, verbose_name='外出状态')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='考勤ID')),
                ('bassepay', models.FloatField(verbose_name='基本工资')),
                ('onday', models.PositiveSmallIntegerField(verbose_name='出勤天数')),
                ('offday', models.PositiveSmallIntegerField(verbose_name='缺勤天数')),
                ('addday', models.PositiveSmallIntegerField(verbose_name='加班天数')),
                ('outday', models.PositiveSmallIntegerField(verbose_name='外出天数')),
                ('salaryMonth', models.DateField(auto_now=True, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='职位ID')),
                ('position_name', models.CharField(max_length=25, verbose_name='职位名称')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('power_id', models.AutoField(primary_key=True, serialize=False, verbose_name='类名')),
                ('modulename', models.CharField(max_length=20, verbose_name='类名')),
                ('classname', models.CharField(max_length=20, verbose_name='类名')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='角色ID')),
                ('role_name', models.CharField(max_length=20, verbose_name='角色名称')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='部门ID')),
                ('section_name', models.CharField(max_length=25, verbose_name='部门名称')),
                ('section_num', models.PositiveIntegerField(verbose_name='部门人数')),
                ('section_remarks', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='员工id')),
                ('staff_name', models.CharField(max_length=20, unique=True, verbose_name='员工姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('birth', models.DateField(auto_now=True)),
                ('photo', models.FileField(upload_to=user.models.user_photo_path)),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('degree', models.CharField(max_length=10, verbose_name='学历')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone_num', models.CharField(max_length=30, verbose_name='电话号码')),
                ('hiredate', models.DateField(auto_now=True, verbose_name='入职日期')),
                ('school', models.CharField(max_length=25, verbose_name='毕业院校')),
                ('staff_remarks', models.TextField(verbose_name='备注')),
                ('position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Position', verbose_name='职位ID')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='部门ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='假期ID')),
                ('yearday', models.PositiveSmallIntegerField(verbose_name='年假')),
                ('illday', models.PositiveSmallIntegerField(verbose_name='病假')),
                ('yearrest', models.PositiveSmallIntegerField(default=0, verbose_name='年休')),
                ('illrest', models.PositiveSmallIntegerField(default=0, verbose_name='病休')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='null', max_length=20, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_passwd',
            field=models.CharField(default='null', max_length=36, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='power',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色ID'),
        ),
        migrations.AddField(
            model_name='position',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色ID'),
        ),
        migrations.AddField(
            model_name='position',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='部门ID'),
        ),
        migrations.AddField(
            model_name='performance',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AddField(
            model_name='out',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色ID'),
        ),
    ]
