# Generated by Django 2.1.2 on 2018-10-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181015_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='out',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
