# Generated by Django 2.1.2 on 2018-10-15 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181015_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='role',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='checkedname',
        ),
        migrations.RemoveField(
            model_name='out',
            name='checkedname',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='performance',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='endday',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='请假结束日期'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(default='请假理由', max_length=200, verbose_name='请假理由'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startday',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='请假起始日期'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default='通知内容', max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AlterField(
            model_name='out',
            name='distingction',
            field=models.CharField(max_length=36, verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='out',
            name='endday',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='外出结束日期'),
        ),
        migrations.AlterField(
            model_name='out',
            name='reason',
            field=models.TextField(default='外出事由', max_length=200, verbose_name='外出事由'),
        ),
        migrations.AlterField(
            model_name='out',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='out',
            name='startday',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='外出起始日期'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='salaryMonth',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='职位ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hiredate',
            field=models.DateField(default=datetime.datetime(2018, 10, 15, 13, 45, 16, 862623), verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.FileField(default='test_1/1.png', upload_to=user.models.user_photo_path),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
        migrations.DeleteModel(
            name='Power',
        ),
    ]
