# Generated by Django 2.1.2 on 2018-10-16 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181016_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='endday',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 207754), verbose_name='请假结束日期'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startday',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 207754), verbose_name='请假起始日期'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='statu',
            field=models.CharField(choices=[('pass', '通过'), ('refuse', '拒绝'), ('unapproved', '未批复')], default='unapproved', max_length=10, verbose_name='批复状态'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AlterField(
            model_name='out',
            name='endday',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 207754), verbose_name='外出结束日期'),
        ),
        migrations.AlterField(
            model_name='out',
            name='startday',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 207754), verbose_name='外出起始日期'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='salaryMonth',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 207754), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 192154), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hiredate',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 16, 44, 25, 192154), verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
