# Generated by Django 2.1.2 on 2018-10-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181017_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='消息时间')),
                ('title', models.CharField(default='个人消息', max_length=20, null=True)),
                ('content', models.TextField(default='个人消息内容', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='addday',
            field=models.FloatField(default=0, verbose_name='加班天数'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='offday',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='缺勤天数'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='onday',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='出勤天数'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='outday',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='外出天数'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
    ]
