# Generated by Django 2.1.2 on 2018-10-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181018_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='通知标题', max_length=20, verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='个人消息内容', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='个人消息', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发送人ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
