# Generated by Django 2.1.2 on 2018-10-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181018_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_passwd',
            field=models.CharField(default='null', max_length=64, verbose_name='密码'),
        ),
    ]
