# Generated by Django 2.1.2 on 2018-10-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181018_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('punch_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='打卡时间')),
                ('late', models.BooleanField(default=False, verbose_name='是否迟到')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='lateday',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='迟到天数'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(max_length=20, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='null', max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='punch',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='员工ID'),
        ),
    ]
