# Generated by Django 2.1.2 on 2018-10-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181019_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_num',
            field=models.PositiveIntegerField(default=0, verbose_name='部门人数'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
